test

diff --git a/.github/workflows/release-advanced.yml b/.github/workflows/release-advanced.yml
--- a/.github/workflows/release-advanced.yml
+++ b/.github/workflows/release-advanced.yml
@@ -34,8 +34,8 @@ jobs:
       - name: Describe latest tag
         id: describe_latest_tag
         run: |
-          tag=$(git describe --tags `git rev-list --tags --max-count=1`) || echo "❌ Error: Terminated";
-                                                                            echo "Reason: Tag not found";
+          tag=$(git describe --tags `git rev-list --tags --max-count=1`) || echo "❌ Error: Terminated" && 
+                                                                            echo "Reason: Tag not found" && 
                                                                             exit 1
           echo "tag=$tag" >> "$GITHUB_OUTPUT"
       - id: extract_version
@@ -53,8 +53,8 @@ jobs:
           
           echo "Detected Version: $MAJOR.$MINOR.$PATCH"
           
-          UPDATE_VERSION=$(jq -r '.version' ./update_trigger.json) || echo "❌ Error: Terminated";
-                                                                      echo "Reason: Version not found";
+          UPDATE_VERSION=$(jq -r '.version' ./update_trigger.json) || echo "❌ Error: Terminated" && 
+                                                                      echo "Reason: Version not found" && 
                                                                       exit 1
           UPDATE_VERSION_NO_V=${UPDATE_VERSION#v}
           
@@ -68,8 +68,8 @@ jobs:
           
           echo "Detected Update Version: $UPDATE_MAJOR.$UPDATE_MINOR.$UPDATE_PATCH"
           
-          PACKAGE_VERSION=$(jq -r '.version' ./package.json) || echo "❌ Error: Terminated";
-                                                                echo "Reason: Version not found";
+          PACKAGE_VERSION=$(jq -r '.version' ./package.json) || echo "❌ Error: Terminated" && 
+                                                                echo "Reason: Version not found" && 
                                                                 exit 1
           PACKAGE_VERSION_NO_V=${PACKAGE_VERSION#v}
           
