test

diff --git a/.github/workflows/release-advanced.yml b/.github/workflows/release-advanced.yml
--- a/.github/workflows/release-advanced.yml
+++ b/.github/workflows/release-advanced.yml
@@ -34,9 +34,9 @@ jobs:
       - name: Describe latest tag
         id: describe_latest_tag
         run: |
-          tag=$(git describe --tags `git rev-list --tags --max-count=1`) || echo "❌ Error: Terminated" && 
-                                                                            echo "Reason: Tag not found" && 
-                                                                            exit 1
+          tag=$(git describe --tags `git rev-list --tags --max-count=1`) 2>/dev/null || echo "❌ Error: Terminated" && 
+                                                                                        echo "Reason: Tag not found" && 
+                                                                                        exit 1
           echo "tag=$tag" >> "$GITHUB_OUTPUT"
       - id: extract_version
         run: |
@@ -53,9 +53,9 @@ jobs:
           
           echo "Detected Version: $MAJOR.$MINOR.$PATCH"
           
-          UPDATE_VERSION=$(jq -r '.version' ./update_trigger.json) || echo "❌ Error: Terminated" && 
-                                                                      echo "Reason: Version not found" && 
-                                                                      exit 1
+          UPDATE_VERSION=$(jq -r '.version' ./update_trigger.json) 2>/dev/null || echo "❌ Error: Terminated" && 
+                                                                                  echo "Reason: Version not found" && 
+                                                                                  exit 1
           UPDATE_VERSION_NO_V=${UPDATE_VERSION#v}
           
           UPDATE_MAJOR=$(echo $UPDATE_VERSION_NO_V | cut -d. -f1)
@@ -68,9 +68,9 @@ jobs:
           
           echo "Detected Update Version: $UPDATE_MAJOR.$UPDATE_MINOR.$UPDATE_PATCH"
           
-          PACKAGE_VERSION=$(jq -r '.version' ./package.json) || echo "❌ Error: Terminated" && 
-                                                                echo "Reason: Version not found" && 
-                                                                exit 1
+          PACKAGE_VERSION=$(jq -r '.version' ./package.json) 2>/dev/null || echo "❌ Error: Terminated" && 
+                                                                            echo "Reason: Version not found" && 
+                                                                            exit 1
           PACKAGE_VERSION_NO_V=${PACKAGE_VERSION#v}
           
           PACKAGE_MAJOR=$(echo $PACKAGE_VERSION_NO_V | cut -d. -f1)
